apiVersion: apps/v1
kind: Deployment
metadata:
  name: dingtalk-hook
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: dingtalk-hook
  template:
    metadata:
      labels:
        app: dingtalk-hook
    spec:
      containers:
        - name: dingtalk-hook
          image: registry.cn-hangzhou.aliyuncs.com/cefso/dingtalk-hook:202310111424
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
              name: http
          env:
            - name: LOG_LEVEL
              value: debug
            - name: ROBOT_TOKEN_PRE
              valueFrom:
                secretKeyRef:
                  name: dingtalk-secret
                  key: token_pre
            - name: ROBOT_SECRET_PRE
              valueFrom:
                secretKeyRef:
                  name: dingtalk-secret
                  key: secret_pre
            - name: ROBOT_TOKEN_PRO
              valueFrom:
                secretKeyRef:
                  name: dingtalk-secret
                  key: token_pro
            - name: ROBOT_SECRET_PRO
              valueFrom:
                secretKeyRef:
                  name: dingtalk-secret
                  key: secret_pro
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 50m
              memory: 100Mi

---
apiVersion: v1
kind: Service
metadata:
  name: dingtalk-hook
  namespace: monitoring
spec:
  selector:
    app: dingtalk-hook
  ports:
    - name: hook
      port: 5000
      targetPort: http
