apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alertmanager-dingtalk-hook.fullname" . }}
  labels:
    {{- include "alertmanager-dingtalk-hook.labels" . | nindent 4 }}
type: Opaque
data:
  secret_pro: {{ .Values.secret.dingtalkPro.secret }}
  token_pro: {{ .Values.secret.dingtalkPro.token }}
  external_url: {{ .Values.secret.externalUrl }}